### ISSUE TITLE
The procedure entry point terminate could not be located in the dynamic link library VCRUNTIME140.dll

### ISSUE THREAD

**Issue by wafflesx90** [Tonic-Box/STLParser#1]
Hello,
As the title says, I am having issues running STLParser. When I run the executable I receive the following error, "The procedure entry point terminate could not be located in the dynamic link library VCRUNTIME140.dll".

I thought this could be easily resolved by replacing the dll, but the issue continues to persist. I have tried the following,
- replaced VCRUNTIME140.dll (two different download locations, checksum looks good.)
- ran sfc/scannow
- scan for possible malware .
- ran a registry cleaner.
- Also, I am running Windows 7 professional 32 bit.
- reinstalled Visual C++ Redistributable for Visual Studio 2015 from Official Microsoft Download.

Thanks,

**Comment by Tonic-Box** [comment]
First, you'll want vs 2019.

**Comment by Tonic-Box** [comment]
You'll want Microsoft Visual C++ 2015-2019 Redistributable Package

Also, why windows 7? Have you tried building the solution yourself?

**Comment by wafflesx90** [comment]
@Tonic-Box ,
I was able to resolve the issue, by your second suggestion of building from source.
Thank you,
